Repository marcelwa/aigverse, pull requests merged in 2025-05, with the labels that each got.

#136 :memo: README emojis
  README.md
  docs/aigs.md
Labels: documentation

#142 :bug: Fix Python version selection in `nox`
  noxfile.py
Labels: bug, tooling

#127 :sparkles: Enable `read_pla` to aig format
  README.md
  bindings/aigverse/__init__.py
  bindings/aigverse/aigverse.cpp
  bindings/aigverse/include/aigverse/io/read_pla.hpp
  bindings/aigverse/pyaigverse.pyi
  bindings/aigverse/test/inout/test_read_pla.py
  bindings/aigverse/test/resources/test.pla
  docs/aigs.md
  docs/example.pla
Labels: enhancement

#137 :sparkles: Index list adapter
  README.md
  bindings/aigverse/__init__.py
  bindings/aigverse/aigverse.cpp
  bindings/aigverse/include/aigverse/adapters/index_list.hpp
  bindings/aigverse/pyaigverse.pyi
  bindings/aigverse/test/adapters/test_index_list.py
  docs/aigs.md
Labels: enhancement

#146 :rewind: Revert dependency changes to fix documentation
  .readthedocs.yaml
  pyproject.toml
Labels: bug, documentation, dependencies
