Repository marcelwa/aigverse, pull requests merged in 2025-04, with the labels that each got.

#109 :memo: RTD fix
  .readthedocs.yaml
  README.md
Labels: bug, documentation

#110 :memo: Update README with documentation link and usage overview
  README.md
Labels: documentation

#120 :construction_worker: Add CodeQL analysis workflow for C++ and Python
  .github/workflows/aigverse-codeql.yml
Labels: github_actions

#119 :memo: Fix `pygraphviz` oversight in documentation
  README.md
  docs/DevelopmentGuide.md
  noxfile.py
Labels: bug, documentation

#116 ✨ Add `FanoutAig` that implements `mockturtle::fanout_view`
  README.md
  bindings/aigverse/__init__.py
  bindings/aigverse/include/aigverse/networks/logic_networks.hpp
  bindings/aigverse/include/aigverse/types.hpp
  bindings/aigverse/pyaigverse.pyi
  bindings/aigverse/test/networks/test_aig.py
  docs/aigs.md
Labels: enhancement

#128 :sparkles: Read/Write Verilog to/from AIGs
  .gitignore
  README.md
  bindings/aigverse/__init__.py
  bindings/aigverse/aigverse.cpp
  bindings/aigverse/include/aigverse/io/read_verilog.hpp
  bindings/aigverse/include/aigverse/io/write_verilog.hpp
  bindings/aigverse/pyaigverse.pyi
  bindings/aigverse/test/inout/test_read_verilog.py
  bindings/aigverse/test/inout/test_write_aiger.py
  bindings/aigverse/test/inout/test_write_verilog.py
  bindings/aigverse/test/resources/test.v
  docs/aigs.md
Labels: enhancement
